sudo: false
bundler_args: "--standalone --binstubs --without development"
script: script/test_all
services: mongodb
before_script:
  - mysql -e 'create database will_paginate;'
  - psql -c 'create database will_paginate;' -U postgres
rvm:
  - 2.1.8
  - 2.2.5
  - 2.3.1
gemfile:
  - Gemfile
  - Gemfile.rails4.2
  - Gemfile.rails5.0
  - Gemfile.rails-edge
matrix:
  exclude:
    - rvm: 2.1.8
      gemfile: Gemfile.rails-edge
    - rvm: 2.1.8
      gemfile: Gemfile.rails5.0
